version: '3.6'
services:
  backend:
    container_name: hono
    build:
      context: ./  
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - ENV=production
      - PORT=3000
      - HOST=0.0.0.0